#!/bin/sh

# create init_modules.cc
# Usage example
# $SRCDIR/src/modules/create_init_modules.sh \
#   "$SRCDIR/src/modules" \
#   "hts_engine" "clunits" "clustergen" > init_modules.cc
# the first argument is the path to festival/src/modules/
# the rest of the args are the modules $(LIB_BUILD_DIRS) $(EXTRA_LIB_BUILD_DIRS) 

src_modules_dir="$1"
shift

echo "/* This file is autogenerated by src/modules/create_init_modules.sh */"
echo ""
echo '#include <cstdio>'
echo '#include "EST_unix.h"'
echo '#include "festival.h"'
echo ""
for module in "$@"; do
  if [ ! -f "${src_modules_dir}/${module}/NoInit" ] ; then \
    echo "void festival_${module}_init(void);"
  fi
done
echo ""
echo "void festival_init_modules(void)"
echo "{"
for module in "$@"; do
  if [ ! -f "${src_modules_dir}/${module}/NoInit" ] ; then \
    echo "    festival_${module}_init();"
  fi
done
echo "}"
echo ""



